### ISSUE TITLE
Missing node FluxPro11UltraRedux

### ISSUE THREAD

**Issue by BtFormado** [gelasdev/ComfyUI-FLUX-BFL-API#8]
Hi There, 

Big thanks for the updates  awesome, but based on the API the ultra also has REDUX support so is missing the node FluxPro11UltraRedux so we can use images on the Ultra model.

Regards,

**Comment by BtFormado** [comment]
> Hi There,
> 
> Big thanks for the updates awesome, but based on the API the ultra also has REDUX support so is missing the node FluxPro11UltraRedux so we can use images on the Ultra model.
> 
> Regards,

I just realise also missing this weight for the redux image :

**Comment by gelasdev** [comment]
Hi

Thanks for feedback. I add both FluxPro11UltraRedux and FluxDevRedux. I also updated workflow.

**Comment by walterFeng** [comment]
@gelasdev Big thanks for the updates awesome. but Do you have plans to add support for flux-pro-1.0-fill？It means a lot to me. Thank you.

**Comment by gelasdev** [comment]
Hello.
It is already added in the current version. Any chance to look in the current version(you can check workflow/BFL-API-tools.json)? Or am I missing something?

![image](https://github.com/user-attachments/assets/8e48b76f-2717-4119-b7dc-423b86fc1887)

**Comment by walterFeng** [comment]
Thanks for your reply. I found that my fill node was reporting an error, and Flux-Pro-1.1 was getting a black picture
![image](https://github.com/user-attachments/assets/6db19180-64e6-4f41-b85e-dd24ebd5d4f8)

This is my local pip dependency：
![image](https://github.com/user-attachments/assets/a02a789e-ec34-4e9f-8564-e743df5e9135)

This is my local git log:
![image](https://github.com/user-attachments/assets/4c0b5be0-3a1a-4456-9415-cfe2de4ffc7e)

any suggestion for me? thank you!

**Comment by walterFeng** [comment]
@gelasdev thanks a lot, It`s my key and start logs:
![image](https://github.com/user-attachments/assets/97765051-722a-4788-b1fe-024435835473)

<details>
<summary>start logs</summary>

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-29 21:18:05.132053
** Platform: Linux
** Python version: 3.10.9 (main, Mar  1 2023, 18:23:06) [GCC 11.2.0]
** Python executable: /home/vipuser/anaconda3/bin/python
** ComfyUI Path: /home/vipuser/ComfyUI
** Log path: /home/vipuser/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Marigold
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   0.3 seconds: /home/vipuser/ComfyUI/custom_nodes/BizyAir
   1.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Manager

Set cuda device to: 0
Total VRAM 81051 MB, total RAM 61394 MB
pytorch version: 2.4.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A800 80GB PCIe : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /home/vipuser/ComfyUI/web
/home/vipuser/anaconda3/lib/python3.10/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
/home/vipuser/anaconda3/lib/python3.10/site-packages/albumentations/check_version.py:49: UserWarning: Error fetching version info The read operation timed out
  data = fetch_version_info()
[Power Noise Suite]: 🦚🦚🦚 Squaaack! 🦚🦚🦚
[Power Noise Suite]: Tamed 11 wild nodes.
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /home/vipuser/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
FizzleDorf Custom Nodes: Loaded
### Loading: ComfyUI Joycaption(V0.1)
Total VRAM 81051 MB, total RAM 61394 MB
pytorch version: 2.4.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A800 80GB PCIe : cudaMallocAsync
/home/vipuser/ComfyUI/custom_nodes/ComfyUI-Marigold/nodes.py:44: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  empty_text_embed = torch.load(os.path.join(script_directory, "empty_text_embed.pt"), map_location="cpu")
Adding /home/vipuser/ComfyUI/custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes Warning: Failed to import python package 'simpleeval'; related nodes disabled.

Loaded Efficiency nodes from /home/vipuser/ComfyUI/custom_nodes/efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from /home/vipuser/ComfyUI/custom_nodes/comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from /home/vipuser/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
### Loading: ComfyUI-Impact-Pack (V7.1)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
### Loading: ComfyUI-Impact-Pack (V7.1)
Loaded ImpactPack nodes from /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
/home/vipuser/anaconda3/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
FaceDetailer: Model directory already exists
FaceDetailer: Model already exists
Display name '☁️BizyAir SetUnionControlNetType' might differ from the native display name.
Display name '☁️BizyAir ControlNetInpaintingAliMamaApply' might differ from the native display name.
Display name '☁️BizyAir DisableNoise' might differ from the native display name.
Display name '☁️BizyAir FlipSigmas' might differ from the native display name.
Display name '☁️BizyAir CFGGuider' might differ from the native display name.
Display name '☁️BizyAir CLIPTextEncodeFlux' might differ from the native display name.
Display name '☁️BizyAir FluxGuidance' might differ from the native display name.
Display name '☁️BizyAir InstructPixToPixConditioning' might differ from the native display name.
Display name '☁️BizyAir IPAdapterModelLoader' might differ from the native display name.
Display name '☁️BizyAir IPAdapterAdvanced' might differ from the native display name.
Display name '☁️BizyAir IPAdapterStyleComposition' might differ from the native display name.
Display name '☁️BizyAir ModelSamplingSD3' might differ from the native display name.
Display name '☁️BizyAir ModelSamplingFlux' might differ from the native display name.
Display name '☁️BizyAir TripleCLIPLoader' might differ from the native display name.
Display name '☁️BizyAir UltimateSDUpscale' might differ from the native display name.
Display name '☁️BizyAir MinusZoneChatGLM3TextEncode' might differ from the native display name.
Display name '☁️BizyAir SamplerCustomAdvanced' might differ from the native display name.
Display name '☁️BizyAir BasicGuider' might differ from the native display name.
Display name '☁️BizyAir BasicScheduler' might differ from the native display name.
Display name '☁️BizyAir DualCLIPLoader' might differ from the native display name.
Display name '☁️BizyAir KSamplerSelect' might differ from the native display name.
Display name '☁️BizyAir RandomNoise' might differ from the native display name.
Display name '☁️BizyAir InpaintModelConditioning' might differ from the native display name.
Display name '☁️BizyAir InpaintModelConditioning_v2' might differ from the native display name.
Display name '☁️BizyAir ConditioningZeroOut' might differ from the native display name.
Display name '☁️BizyAir ConditioningSetTimestepRange' might differ from the native display name.


[BizyAir] Model hosting service initialized.


[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ckpts path: /home/vipuser/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using symlinks: False
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)
[Crystools INFO] Crystools version: 1.16.6
[Crystools INFO] CPU: Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz - Arch: x86_64 - OS: Linux 6.2.0-35-generic
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA A800 80GB PCIe
[Crystools INFO] NVIDIA Driver: 535.113.01
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...

[rgthree] Loaded 42 extraordinary nodes.
[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.

### Loading: ComfyUI-Manager (V2.50.1)
### ComfyUI Revision: 2622 [38c22e63] *DETACHED | Released on '2024-08-27'
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
/home/vipuser/ComfyUI
############################################
/home/vipuser/ComfyUI/custom_nodes/ComfyUI-NAI-styler/CSV
############################################
[]
############################################
LOADED 5 FONTS


███╗   ███╗ █████╗  ██████╗██╗  ██╗██╗███╗   ██╗███████╗
████╗ ████║██╔══██╗██╔════╝██║  ██║██║████╗  ██║██╔════╝
██╔████╔██║███████║██║     ███████║██║██╔██╗ ██║█████╗
██║╚██╔╝██║██╔══██║██║     ██╔══██║██║██║╚██╗██║██╔══╝
██║ ╚═╝ ██║██║  ██║╚██████╗██║  ██║██║██║ ╚████║███████╗
╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝

██████╗ ███████╗██╗     ██╗   ██╗███████╗██╗ ██████╗ ███╗   ██╗███████╗
██╔══██╗██╔════╝██║     ██║   ██║██╔════╝██║██╔═══██╗████╗  ██║██╔════╝
██║  ██║█████╗  ██║     ██║   ██║███████╗██║██║   ██║██╔██╗ ██║███████╗
██║  ██║██╔══╝  ██║     ██║   ██║╚════██║██║██║   ██║██║╚██╗██║╚════██║
██████╔╝███████╗███████╗╚██████╔╝███████║██║╚██████╔╝██║ ╚████║███████║
╚═════╝ ╚══════╝╚══════╝ ╚═════╝ ╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝



Comfy-Easy-Use v1.2.2: Loaded
### Loading: ComfyUI-Impact-Pack (V7.1)
[Impact Pack] Wildcards loading done.
# 😺dzNodes: LayerStyle -> Warning: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_LayerStyle/resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Find 1 LUTs in /home/vipuser/ComfyUI/custom_nodes/ComfyUI_LayerStyle/lut
# 😺dzNodes: LayerStyle -> Find 1 Fonts in /home/vipuser/ComfyUI/custom_nodes/ComfyUI_LayerStyle/font
json_repair## OK
--------------
 ### Mixlab Nodes: Loaded
ChatGPT.available True
edit_mask.available True
simple_lama_inpainting## OK
LaMaInpainting.available True
ClipInterrogator.available True
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
TripoSR.available
 --------------
Patching UNetModel.forward
UNetModel.forward has been successfully patched.
### [START] ComfyUI AlekPet Nodes v1.0.16 ###
Node -> DeepTranslatorNode: DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode [Loading]
Node -> ArgosTranslateNode: ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode [Loading]
Node -> GoogleTranslateNode: GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode [Loading]
Node -> ExtrasNode: PreviewTextNode, HexToHueNode, ColorsCorrectNode [Loading]
Node -> PoseNode: PoseNode [Loading]
Node -> IDENode: IDENode [Loading]
Node -> PainterNode: PainterNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
### Loading: ComfyUI-Inspire-Pack (V0.86)
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/home/vipuser/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 219 nodes successfully.

	"Art is the soul made visible." - George Crook

[ReActor] - STATUS - Running v0.5.1-a6 in ComfyUI
Torch version: 2.4.0+cu121

Import times for custom nodes:
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Photopea
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/AIGODLIKE-ComfyUI-Translation
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/cg-use-everywhere
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ControlNet-LLLite-ComfyUI
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-BRIA_AI-RMBG
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Inpaint-CropAndStitch
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_TiledKSampler
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/FreeU_Advanced
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Universal-Styler
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/stability-ComfyUI-nodes
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-IC-Light
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/bfl-comfy-nodes
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/PowerNoiseSuite
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_FaceShaper
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_InstantID
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-FLUX-BFL-API
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/cg-image-picker
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_experiments
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-safety-checker
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/comfy-plasma
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/wlsh_nodes
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_essentials
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Florence2
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/comfyui-inpaint-nodes
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Image-Utils
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-KJNodes
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-segment-anything-2
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/comfyui-workspace-manager
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-BrushNet
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-GGUF
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/images-grid-comfy-plugin
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/comfyui-ollama
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/comfyui-dynamicprompts
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/comfyui-joycaption
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/x-flux-comfyui
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-AnimateDiff
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-KwaiKolorsWrapper
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Anyline
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/Comfyui_ALY
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_LayerStyle
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   0.0 seconds: /home/vipuser/ComfyUI/custom_nodes/comfyui_segment_anything
   0.1 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.1 seconds: /home/vipuser/ComfyUI/custom_nodes/comfyui-reactor-node
   0.1 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Crystools
   0.1 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_bitsandbytes_NF4
   0.1 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Marigold
   0.2 seconds: /home/vipuser/ComfyUI/custom_nodes/DZ-FaceDetailer
   0.3 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_FizzNodes
   0.4 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Gemini
   0.4 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-SUPIR
   0.6 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-Inspyrenet-Rembg
   0.8 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_Fill-Nodes
   0.9 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet
   0.9 seconds: /home/vipuser/ComfyUI/custom_nodes/comfyui-mixlab-nodes
   1.5 seconds: /home/vipuser/ComfyUI/custom_nodes/was-node-suite-comfyui
   2.4 seconds: /home/vipuser/ComfyUI/custom_nodes/comfyui-art-venture
   3.7 seconds: /home/vipuser/ComfyUI/custom_nodes/BizyAir
   8.1 seconds: /home/vipuser/ComfyUI/custom_nodes/ComfyUI-PhotoMaker-Plus





Starting server
Error starting the server: [Errno -2] Name or service not known
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
got prompt
invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because a node is missing the class_type property.', 'details': "Node ID '#29'", 'extra_info': {}}
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json

</details>

**Comment by gelasdev** [comment]
Can you check node manager maybe node not updated and need restart. I deleted node from manager and reinstall it. Then update api key. All node worked from my side. And maybe check ComftUI version. I use latest one.
<img width="1328" alt="Screenshot 2024-11-29 at 16 39 11" src="https://github.com/user-attachments/assets/ded954d5-ad14-4246-a707-859cd898bca8">

**Comment by walterFeng** [comment]
I just tried to delete the node from manager and reinstall it, then updated the api, and restarted my comfyUI. The problem I encountered was the same as before, and I used other nodes to verify that my key was OK. Maybe as you said, I should update my comfyUI, but it may take a little time to try. Thanks for your help @gelasdev 
![image](https://github.com/user-attachments/assets/e4f98f3e-5f51-4bcd-bca8-6e192874c53d)

**Comment by gelasdev** [comment]
I'm sorry I couldn't help. I couldn't produce the error. I will try on another pc this evening. Maybe then i can help. You can open another issue so we can track issue from there.

**Comment by walterFeng** [comment]
> I'm sorry I couldn't help. I couldn't produce the error. I will try on another pc this evening. Maybe then i can help. You can open another issue so we can track issue from there.

@gelasdev I update my comfyUI to latest,and all is working now.   Thank you so much for the open source, it's great!
